name: testing input workflows

on:
  workflow_dispatch
   
jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking Secret Variables"
        run: echo "Secret Value ${{secrets.ERP_KEY}}"
